### ISSUE TITLE
Affichage du nombre d'inscription depuis la page du meetup

### ISSUE THREAD

**Issue by alexisjanvier** [CaenCamp/new-website#21]
Afficher le nombre d'inscrits à une rencontre depuis l'API meetup.

**Comment by Zevran** [comment]
Tu veux afficher le nombre d'inscrits à chaque rencontre ? Y compris celles qui sont déjà passées ?

**Comment by alexisjanvier** [comment]
Non, je me disais que ce serait surtout pour le meetup à venir.

**Comment by Zevran** [comment]
Arf mince du coup je t'ai fait une pr qui correspond pas du tout à ce qui est voulue xD

**Comment by Zevran** [comment]
J'ai ajouté la prochaine rencontre dans le composant SideMenu, si tu veux tester l'affichage il faut remplacer la valeur du filtre `status` avec `past` dans la requête graphql.

**Comment by alexisjanvier** [comment]
Closed with #33
