### ISSUE TITLE
Filtrer les talks par tags

### ISSUE THREAD

**Issue by alexisjanvier** [CaenCamp/new-website#22]
Chaque talk possède maintenant un ou plusieurs tags : 
![capture d ecran de 2018-01-28 11-52-31](https://user-images.githubusercontent.com/547706/35481331-d370c672-0421-11e8-8f44-c7b12fbc1026.png)

Il faudra ajouter la possibilité de filtrer la liste de talks par tag.

**Comment by amenophis** [comment]
Je m'occupe de celle la :)
