### ISSUE TITLE
L'affichage des dates de talks est cassé sous Firefox et Safari

### ISSUE THREAD

**Issue by alexisjanvier** [CaenCamp/new-website#51]
L'affichage des dates est correct sous **Chrome**
![capture d ecran de 2018-10-03 07-47-46](https://user-images.githubusercontent.com/547706/46392828-0a733b80-c6e3-11e8-8366-0afd340e1dc8.png)

Par contre il est cassé sous **Firefox**
![capture d ecran de 2018-10-03 07-47-29](https://user-images.githubusercontent.com/547706/46392841-13fca380-c6e3-11e8-8278-9aa975ca4578.png)

et sous **Safari**
![capture d ecran 2018-10-03 a 07 50 30](https://user-images.githubusercontent.com/547706/46392854-1fe86580-c6e3-11e8-8477-7decbfd67b1a.png)

**Comment by Lakston** [comment]
PR: #58

**Comment by alexisjanvier** [comment]
Close with #58
