### ISSUE TITLE
Player vidéo

### ISSUE THREAD

**Issue by alexisjanvier** [CaenCamp/new-website#54]
Nous utilisons pour le moment le module [react-player](https://github.com/CookPete/react-player) pour afficher les vidéos.

![capture d ecran de 2018-10-03 08-31-20](https://user-images.githubusercontent.com/547706/46393754-ceda7080-c6e6-11e8-9bdc-338431ce0ac9.png)

Un gros avantage est qu'il accepte aussi bien les vidéos YouTube que Viméo. Mais tel qu'il est configuré, il n'affiche pas les contrôles de lecture YouTube.

Il faudrait voir si il peut être mieux configurer, ou si nous pourrions mettre en place un autre player.

**Comment by Clebiez** [comment]
Et bien je vais voir ce que je peux faire !
