### ISSUE TITLE
Mettre à jour le Storybook

### ISSUE THREAD

**Issue by alexisjanvier** [CaenCamp/new-website#60]
https://storybook.js.org/

**Comment by alexisjanvier** [comment]
Je dirais qu'il y a deux taches liées à cette issue : 

* Mettre à jour la version du storyBook,
* Passer les principaux éléments graphiques dans le storyBook (vues listes, dates, intervenants, ...)

**Comment by EricTurf** [comment]
De se que j'ai vu en ligne, il faut mettre a jour `Gatsby` pour resoudre une des erreures avec storybook. Donc je peut travailler sur storybook quand #63 est merged

**Comment by alexisjanvier** [comment]
Close because storybook has been removed.
